"""Add new models and schema changes: users, articles, categories, company_files, company_profile, intents

Revision ID: 577f269a3899
Revises: 3694c55adf2b
Create Date: 2025-11-18 19:18:19.550529

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "577f269a3899"
down_revision: Union[str, Sequence[str], None] = "3694c55adf2b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		"categories",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("name", sa.String(length=255), nullable=False),
		sa.Column("level", sa.Integer(), nullable=False),
		sa.Column("parent_id", sa.Integer(), nullable=True),
		sa.Column(
			"created_at",
			sa.DateTime(),
			server_default=sa.text("CURRENT_TIMESTAMP"),
			nullable=False,
		),
		sa.Column(
			"updated_at",
			sa.DateTime(),
			server_default=sa.text("CURRENT_TIMESTAMP"),
			nullable=True,
		),
		sa.CheckConstraint(
			"(level = 1 AND parent_id IS NULL) OR (level > 1 AND parent_id IS NOT NULL)",
			name="check_parent_by_level",
		),
		sa.CheckConstraint("level BETWEEN 1 AND 3", name="check_level_range"),
		sa.ForeignKeyConstraint(
			["parent_id"],
			["categories.id"],
		),
		sa.PrimaryKeyConstraint("id"),
	)
	op.create_index(op.f("ix_categories_id"), "categories", ["id"], unique=False)
	op.create_table(
		"company_files",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("area", sa.String(length=255), nullable=True),
		sa.Column("blob_path", sa.String(length=1000), nullable=False),
		sa.Column("original_filename", sa.String(length=255), nullable=False),
		sa.Column(
			"created_at",
			sa.DateTime(),
			server_default=sa.text("CURRENT_TIMESTAMP"),
			nullable=False,
		),
		sa.Column(
			"updated_at",
			sa.DateTime(),
			server_default=sa.text("CURRENT_TIMESTAMP"),
			nullable=True,
		),
		sa.PrimaryKeyConstraint("id"),
	)
	op.create_index(op.f("ix_company_files_id"), "company_files", ["id"], unique=False)
	op.create_table(
		"company_profile",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("name", sa.String(length=255), nullable=False),
		sa.Column("domain", sa.String(length=255), nullable=True),
		sa.Column("industry", sa.String(length=100), nullable=True),
		sa.Column("support_email", sa.String(length=255), nullable=True),
		sa.Column(
			"created_at",
			sa.DateTime(),
			server_default=sa.text("CURRENT_TIMESTAMP"),
			nullable=False,
		),
		sa.Column(
			"updated_at",
			sa.DateTime(),
			server_default=sa.text("CURRENT_TIMESTAMP"),
			nullable=True,
		),
		sa.PrimaryKeyConstraint("id"),
		sa.UniqueConstraint("support_email"),
	)
	op.create_index(
		op.f("ix_company_profile_id"), "company_profile", ["id"], unique=False
	)
	op.create_table(
		"users",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("name", sa.String(length=255), nullable=False),
		sa.Column("email", sa.String(length=255), nullable=False),
		sa.Column("role", sa.String(length=100), nullable=False),
		sa.Column("area", sa.String(length=255), nullable=True),
		sa.Column("slack_user_id", sa.String(length=255), nullable=False),
		sa.Column(
			"created_at",
			sa.DateTime(),
			server_default=sa.text("CURRENT_TIMESTAMP"),
			nullable=False,
		),
		sa.Column(
			"updated_at",
			sa.DateTime(),
			server_default=sa.text("CURRENT_TIMESTAMP"),
			nullable=True,
		),
		sa.PrimaryKeyConstraint("id"),
	)
	op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
	op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
	op.create_table(
		"intents",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("name", sa.String(length=255), nullable=False),
		sa.Column("category_level_1_id", sa.Integer(), nullable=True),
		sa.Column("category_level_2_id", sa.Integer(), nullable=True),
		sa.Column("category_level_3_id", sa.Integer(), nullable=True),
		sa.Column("area", sa.String(length=255), nullable=True),
		sa.Column(
			"is_processed",
			sa.Boolean(),
			server_default=sa.text("FALSE"),
			nullable=False,
		),
		sa.Column(
			"created_at",
			sa.DateTime(),
			server_default=sa.text("CURRENT_TIMESTAMP"),
			nullable=False,
		),
		sa.Column(
			"updated_at",
			sa.DateTime(),
			server_default=sa.text("CURRENT_TIMESTAMP"),
			nullable=True,
		),
		sa.ForeignKeyConstraint(
			["category_level_1_id"],
			["categories.id"],
		),
		sa.ForeignKeyConstraint(
			["category_level_2_id"],
			["categories.id"],
		),
		sa.ForeignKeyConstraint(
			["category_level_3_id"],
			["categories.id"],
		),
		sa.PrimaryKeyConstraint("id"),
	)
	op.create_index(op.f("ix_intents_id"), "intents", ["id"], unique=False)
	op.create_table(
		"articles",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("intent_id", sa.Integer(), nullable=False),
		sa.Column("type", sa.String(length=10), nullable=False),
		sa.Column("blob_path", sa.String(length=1000), nullable=False),
		sa.Column(
			"status",
			sa.String(length=20),
			server_default=sa.text("'iteration'"),
			nullable=False,
		),
		sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
		sa.Column("feedback", sa.Text(), nullable=True),
		sa.Column(
			"created_at",
			sa.DateTime(),
			server_default=sa.text("CURRENT_TIMESTAMP"),
			nullable=False,
		),
		sa.Column(
			"updated_at",
			sa.DateTime(),
			server_default=sa.text("CURRENT_TIMESTAMP"),
			nullable=True,
		),
		sa.CheckConstraint(
			"status IN ('iteration', 'accepted', 'denied')", name="check_article_status"
		),
		sa.ForeignKeyConstraint(
			["intent_id"],
			["intents.id"],
		),
		sa.PrimaryKeyConstraint("id"),
	)
	op.create_index(op.f("ix_articles_id"), "articles", ["id"], unique=False)
	op.drop_table("link")
	op.drop_table("user")
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		"user",
		sa.Column("user_id", mysql.VARCHAR(length=299), nullable=False),
		sa.Column("displayable_name", mysql.VARCHAR(length=100), nullable=False),
		sa.Column("email", mysql.VARCHAR(length=100), nullable=False),
		sa.Column("profile_pic_object_name", mysql.VARCHAR(length=299), nullable=False),
		sa.Column("country", mysql.VARCHAR(length=299), nullable=False),
		sa.Column(
			"timeRegistered",
			mysql.TIMESTAMP(),
			server_default=sa.text("CURRENT_TIMESTAMP"),
			nullable=True,
		),
		sa.Column(
			"isAdmin",
			mysql.TINYINT(display_width=1),
			server_default=sa.text("'0'"),
			autoincrement=False,
			nullable=True,
		),
		sa.PrimaryKeyConstraint("user_id"),
		mysql_collate="utf8mb4_0900_ai_ci",
		mysql_default_charset="utf8mb4",
		mysql_engine="InnoDB",
	)
	op.create_table(
		"link",
		sa.Column("link_id", mysql.INTEGER(), autoincrement=True, nullable=False),
		sa.Column("creator_id", mysql.VARCHAR(length=299), nullable=False),
		sa.Column("old_link", mysql.VARCHAR(length=299), nullable=False),
		sa.Column("new_link", mysql.VARCHAR(length=299), nullable=False),
		sa.Column("expires_at", mysql.DATETIME(), nullable=True),
		sa.Column(
			"timeRegistered",
			mysql.DATETIME(),
			server_default=sa.text("CURRENT_TIMESTAMP"),
			nullable=True,
		),
		sa.Column(
			"click_count",
			mysql.INTEGER(),
			server_default=sa.text("'0'"),
			autoincrement=False,
			nullable=True,
		),
		sa.ForeignKeyConstraint(
			["creator_id"], ["user.user_id"], name=op.f("link_ibfk_1")
		),
		sa.PrimaryKeyConstraint("link_id"),
		mysql_collate="utf8mb4_0900_ai_ci",
		mysql_default_charset="utf8mb4",
		mysql_engine="InnoDB",
	)
	op.drop_index(op.f("ix_articles_id"), table_name="articles")
	op.drop_table("articles")
	op.drop_index(op.f("ix_intents_id"), table_name="intents")
	op.drop_table("intents")
	op.drop_index(op.f("ix_users_id"), table_name="users")
	op.drop_index(op.f("ix_users_email"), table_name="users")
	op.drop_table("users")
	op.drop_index(op.f("ix_company_profile_id"), table_name="company_profile")
	op.drop_table("company_profile")
	op.drop_index(op.f("ix_company_files_id"), table_name="company_files")
	op.drop_table("company_files")
	op.drop_index(op.f("ix_categories_id"), table_name="categories")
	op.drop_table("categories")
	# ### end Alembic commands ###
