"""sync models with db: update tickets and related tables

Revision ID: 78ab650fd335
Revises: ee5d0bee46ad
Create Date: 2025-11-20 20:27:27.915167

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "78ab650fd335"
down_revision: Union[str, Sequence[str], None] = "ee5d0bee46ad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_constraint(op.f("tickets_ibfk_1"), "tickets", type_="foreignkey")
	op.create_foreign_key(
		None, "tickets", "intents", ["intent_id"], ["id"], ondelete="SET NULL"
	)
	op.execute(
		"ALTER TABLE tickets MODIFY updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_constraint(None, "tickets", type_="foreignkey")
	op.create_foreign_key(
		op.f("tickets_ibfk_1"), "tickets", "intents", ["intent_id"], ["id"]
	)
	op.execute(
		"ALTER TABLE tickets MODIFY updated_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP"
	)
	# ### end Alembic commands ###
